apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlitespeed
  labels:
    app: openlitespeed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openlitespeed
  template:
    metadata:
      labels:
        app: openlitespeed
    spec:
      containers:
      - name: openlitespeed
        image: litespeedtech/openlitespeed:latest
        ports:
        - containerPort: 8088
